name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get the version
        id: get-tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          target: release-debian
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tx-task:${{steps.get-tag.outputs.tag}}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/tx-task:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/tx-task:buildcache,mode=max