name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: |
            helm uninstall hello -n hello --wait
          # helm uninstall hello -n hello --wait --dry-run # stimulate uninstall 
